name: Python Test

on:
  push

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Py-prep
        run: make py-prep
      - name: Test
        run: |
          source .venv/bin/activate
          pytest
      - name: Check Schemas
        run: make migrate_up_sqlite && make update-schema && git diff --exit-code
      - name: Wheel
        run: |
          make ui
          make uv-wheel
